In [31]:
import numpy as np
import matplotlib as plt
import pandas as pd
import os
import sys

In [20]:
ruta = os.getcwd() + "\\GIIP"

with os.scandir(ruta) as Folder:
    Ficheros = [Folder.name for Folder in Folder if Folder.is_dir()]

print(Ficheros)

['61-66', '8', '19-24', '187-192', '5', '103-108', '235-240', '1', '2', '32', '193-198', '49-54', '35', '4', '169-174', '25-30', '145-150', '97-102', '31', '10', '66', '7', '67-72', '253-258', '55-60', '127-132', '181-186', '13-18', '.ipynb_checkpoints', '73-78', '37-42', '9', '6', '31-36', '229-234', '241-246', '163-168', '211-216', '223-228', '265-270', '36', '7-12', '247-252', '157-162', '79-84', '151-156', '259-264', '85-90', '1-6', '115-120', '199-204', '175-180', '91-96', '205-210', '139-144', '109-114', '43-48', '.git', '3', '217-222', '121-126', '133-138', '34', '33']


In [27]:
Rut_Extract = os.getcwd() + "\\" + "61-66" + "\\Extract"
print(Rut_Extract)

\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\61-66\Extract


In [38]:
pwd

'\\\\wsl.localhost\\Ubuntu-18.04\\home\\juanubuntu1804\\MODELOS\\MODELOSGIIP'

In [53]:
#def read_Extract(filePath):
    
    # initialize 
means = np.zeros(4)
sigs  = np.zeros(4)
N = 0

data = []

    # collect data
#try:
f = open("Extract",'r')
#f = pd.read_csv ("Extract", sep = " ")
#except IOError:
    #print("Could not open file '{}' for reading".format(Rut_Extract))
    #return tuple()


#with f as myfile:
#    total_lines = sum(1 for line in myfile)
#print(total_lines)

for line in f:
    try:    
        vals = np.array([ float(s) for s in line.strip().split(' ') ])
        print(vals)
    except IOError:
        print(line)
 
    

 #       N += 1
 #       means += vals         # collecting x_i
 #       sigs  += vals*vals    # collecting x_i^2
#
#        data.append(vals)

    # finish up calculations    
 #   means /= N
 #   sigs = np.sqrt(sigs/N - means*means)

 #   for i in range(len(means)):
 #       print("data in column {:2d} -> mean={:12.8f}   stdev={:12.8f}".format(i, means[i],sigs[i]))
 #       
    # convert data into a multi-dimensional numpy.array
    #return np.array(data)

ValueError: could not convert string to float: 'FenderFace'

In [26]:
for Nom_Fic in Ficheros:
    print(Nom_Fic)
    Rut_Atero = os.getcwd() + "\\" + Nom_Fic + "\\AterroExtract"
    Rut_Extract = os.getcwd() + "\\" + Nom_Fic + "\\Extract"
    print(Rut_Atero)
    print(Rut_Extract)

61-66
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\61-66\Aterro
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\61-66\Extract
8
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\8\Aterro
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\8\Extract
19-24
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\19-24\Aterro
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\19-24\Extract
187-192
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\187-192\Aterro
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\187-192\Extract
5
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\5\Aterro
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\5\Extract
103-108
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\103-108\Aterro
\\wsl.localhost\Ubuntu-18.04\home\juanubuntu1804\MODELOS\MODELOSGIIP\10

In [9]:
a= np.load("ExtractConfNumpy")

In [10]:
a

array([[-6.98400000e+05,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -9.37834267e+06,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -2.40016540e-09,
         1.69135594e-10, -3.04046948e+04, -3.95594384e+03,
         3.98480335e-09,  9.97502061e-10],
       [ 0.00000000e+00, -7.65024134e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00]])

In [25]:
results=np.zeros((1,9),dtype=float)

In [22]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
a[0][0]

-698399.9999965916

In [28]:
results[0][0]=a[0][0]
results[0][1]=a[1][1]
results[0][2]=a[2][2]
results[0][3]=a[2][3]
results[0][4]=a[2][4]
results[0][5]=a[2][5]
results[0][6]=a[2][6]
results[0][7]=a[2][7]
results[0][8]=a[3][1]
b

array([[-6.98400000e+05, -9.37834267e+06, -2.40016540e-09,
         1.69135594e-10, -3.04046948e+04, -3.95594384e+03,
         3.98480335e-09,  9.97502061e-10, -7.65024134e-02]])